### ISSUE TITLE
ClassNotFound log4j

### ISSUE THREAD

**Issue by wheel1992** [graphhopper/jsprit#237]
Hi, I've tried to build the project and this error shows up. I've downloaded a few log4j versions and all package name is under org.apache.log4j.xxx instead of org.apache.logging.log4j.xxx.

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at jsprit.core.problem.vehicle.VehicleImpl$Builder.<clinit>(VehicleImpl.java:110)
	at MainApplication.main(MainApplication.java:37)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more`

**Comment by karussell** [comment]
Please use the forum to discuss a problem. This is highly likely not a bug as [travis](https://travis-ci.org/graphhopper/jsprit) proves it :)
